/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/create': RouteRecordInfo<
      '/create',
      '/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design-system': RouteRecordInfo<
      '/design-system',
      '/design-system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/settings/general/about'
      | '/settings/general/appearance'
      | '/settings/share/gists'
    >,
    '/settings/general/about': RouteRecordInfo<
      '/settings/general/about',
      '/settings/general/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/general/appearance': RouteRecordInfo<
      '/settings/general/appearance',
      '/settings/general/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/share/gists': RouteRecordInfo<
      '/settings/share/gists',
      '/settings/share/gists',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tournament/[tournamentId]': RouteRecordInfo<
      '/tournament/[tournamentId]',
      '/tournament/:tournamentId',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | '/tournament/[tournamentId]/'
      | '/tournament/[tournamentId]/about'
      | '/tournament/[tournamentId]/config'
      | '/tournament/[tournamentId]/config/advanced/debug'
      | '/tournament/[tournamentId]/config/advanced/edit'
      | '/tournament/[tournamentId]/config/edit/danger'
      | '/tournament/[tournamentId]/config/edit/plan'
      | '/tournament/[tournamentId]/config/edit/teams'
      | '/tournament/[tournamentId]/config/share/gists'
      | '/tournament/[tournamentId]/knockout'
      | '/tournament/[tournamentId]/live'
      | '/tournament/[tournamentId]/matches'
      | '/tournament/[tournamentId]/table'
    >,
    '/tournament/[tournamentId]/': RouteRecordInfo<
      '/tournament/[tournamentId]/',
      '/tournament/:tournamentId',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournament/[tournamentId]/about': RouteRecordInfo<
      '/tournament/[tournamentId]/about',
      '/tournament/:tournamentId/about',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournament/[tournamentId]/config': RouteRecordInfo<
      '/tournament/[tournamentId]/config',
      '/tournament/:tournamentId/config',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | '/tournament/[tournamentId]/config/advanced/debug'
      | '/tournament/[tournamentId]/config/advanced/edit'
      | '/tournament/[tournamentId]/config/edit/danger'
      | '/tournament/[tournamentId]/config/edit/plan'
      | '/tournament/[tournamentId]/config/edit/teams'
      | '/tournament/[tournamentId]/config/share/gists'
    >,
    '/tournament/[tournamentId]/config/advanced/debug': RouteRecordInfo<
      '/tournament/[tournamentId]/config/advanced/debug',
      '/tournament/:tournamentId/config/advanced/debug',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournament/[tournamentId]/config/advanced/edit': RouteRecordInfo<
      '/tournament/[tournamentId]/config/advanced/edit',
      '/tournament/:tournamentId/config/advanced/edit',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournament/[tournamentId]/config/edit/danger': RouteRecordInfo<
      '/tournament/[tournamentId]/config/edit/danger',
      '/tournament/:tournamentId/config/edit/danger',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournament/[tournamentId]/config/edit/plan': RouteRecordInfo<
      '/tournament/[tournamentId]/config/edit/plan',
      '/tournament/:tournamentId/config/edit/plan',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournament/[tournamentId]/config/edit/teams': RouteRecordInfo<
      '/tournament/[tournamentId]/config/edit/teams',
      '/tournament/:tournamentId/config/edit/teams',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournament/[tournamentId]/config/share/gists': RouteRecordInfo<
      '/tournament/[tournamentId]/config/share/gists',
      '/tournament/:tournamentId/config/share/gists',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournament/[tournamentId]/knockout': RouteRecordInfo<
      '/tournament/[tournamentId]/knockout',
      '/tournament/:tournamentId/knockout',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournament/[tournamentId]/live': RouteRecordInfo<
      '/tournament/[tournamentId]/live',
      '/tournament/:tournamentId/live',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournament/[tournamentId]/matches': RouteRecordInfo<
      '/tournament/[tournamentId]/matches',
      '/tournament/:tournamentId/matches',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournament/[tournamentId]/table': RouteRecordInfo<
      '/tournament/[tournamentId]/table',
      '/tournament/:tournamentId/table',
      { tournamentId: ParamValue<true> },
      { tournamentId: ParamValue<false> },
      | never
    >,
    '/tournaments': RouteRecordInfo<
      '/tournaments',
      '/tournaments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/create.vue': {
      routes:
        | '/create'
      views:
        | never
    }
    'src/pages/design-system.vue': {
      routes:
        | '/design-system'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
        | '/settings/general/about'
        | '/settings/general/appearance'
        | '/settings/share/gists'
      views:
        | 'default'
    }
    'src/pages/settings/general/about.vue': {
      routes:
        | '/settings/general/about'
      views:
        | never
    }
    'src/pages/settings/general/appearance.vue': {
      routes:
        | '/settings/general/appearance'
      views:
        | never
    }
    'src/pages/settings/share/gists.vue': {
      routes:
        | '/settings/share/gists'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId].vue': {
      routes:
        | '/tournament/[tournamentId]'
        | '/tournament/[tournamentId]/'
        | '/tournament/[tournamentId]/about'
        | '/tournament/[tournamentId]/config'
        | '/tournament/[tournamentId]/config/advanced/debug'
        | '/tournament/[tournamentId]/config/advanced/edit'
        | '/tournament/[tournamentId]/config/edit/danger'
        | '/tournament/[tournamentId]/config/edit/plan'
        | '/tournament/[tournamentId]/config/edit/teams'
        | '/tournament/[tournamentId]/config/share/gists'
        | '/tournament/[tournamentId]/knockout'
        | '/tournament/[tournamentId]/live'
        | '/tournament/[tournamentId]/matches'
        | '/tournament/[tournamentId]/table'
      views:
        | 'default'
    }
    'src/pages/tournament/[tournamentId]/index.vue': {
      routes:
        | '/tournament/[tournamentId]/'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId]/about.vue': {
      routes:
        | '/tournament/[tournamentId]/about'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId]/config.vue': {
      routes:
        | '/tournament/[tournamentId]/config'
        | '/tournament/[tournamentId]/config/advanced/debug'
        | '/tournament/[tournamentId]/config/advanced/edit'
        | '/tournament/[tournamentId]/config/edit/danger'
        | '/tournament/[tournamentId]/config/edit/plan'
        | '/tournament/[tournamentId]/config/edit/teams'
        | '/tournament/[tournamentId]/config/share/gists'
      views:
        | 'default'
    }
    'src/pages/tournament/[tournamentId]/config/advanced/debug.vue': {
      routes:
        | '/tournament/[tournamentId]/config/advanced/debug'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId]/config/advanced/edit.vue': {
      routes:
        | '/tournament/[tournamentId]/config/advanced/edit'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId]/config/edit/danger.vue': {
      routes:
        | '/tournament/[tournamentId]/config/edit/danger'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId]/config/edit/plan.vue': {
      routes:
        | '/tournament/[tournamentId]/config/edit/plan'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId]/config/edit/teams.vue': {
      routes:
        | '/tournament/[tournamentId]/config/edit/teams'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId]/config/share/gists.vue': {
      routes:
        | '/tournament/[tournamentId]/config/share/gists'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId]/knockout.vue': {
      routes:
        | '/tournament/[tournamentId]/knockout'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId]/live.vue': {
      routes:
        | '/tournament/[tournamentId]/live'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId]/matches.vue': {
      routes:
        | '/tournament/[tournamentId]/matches'
      views:
        | never
    }
    'src/pages/tournament/[tournamentId]/table.vue': {
      routes:
        | '/tournament/[tournamentId]/table'
      views:
        | never
    }
    'src/pages/tournaments.vue': {
      routes:
        | '/tournaments'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
